// lib/evaluationData.js

// SOP 1 — Recognition (Type / Make / Model)
export const sop1Recognition = [
  {
    level: "Type",
    metrics: [
      {
        metric: "Accuracy",
        baseline: 0.872,
        cmt: 0.94,
        delta: 0.068,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Precision",
        baseline: 0.864,
        cmt: 0.93,
        delta: 0.066,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Recall",
        baseline: 0.853,
        cmt: 0.919,
        delta: 0.066,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "F1",
        baseline: 0.865,
        cmt: 0.93,
        delta: 0.065,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
    ],
  },
  {
    level: "Make",
    metrics: [
      {
        metric: "Accuracy",
        baseline: 0.816,
        cmt: 0.89,
        delta: 0.074,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Precision",
        baseline: 0.79,
        cmt: 0.866,
        delta: 0.075,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Recall",
        baseline: 0.799,
        cmt: 0.885,
        delta: 0.086,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "F1",
        baseline: 0.799,
        cmt: 0.881,
        delta: 0.082,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
    ],
  },
  {
    level: "Model",
    metrics: [
      {
        metric: "Accuracy",
        baseline: 0.755,
        cmt: 0.835,
        delta: 0.08,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Precision",
        baseline: 0.73,
        cmt: 0.807,
        delta: 0.077,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "Recall",
        baseline: 0.734,
        cmt: 0.817,
        delta: 0.083,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
      {
        metric: "F1",
        baseline: 0.738,
        cmt: 0.818,
        delta: 0.08,
        W: 0,
        p: 0.0,
        interpretation: "Significant improvement",
      },
    ],
  },
];

// SOP 2 — Localization (Vehicle box + parts mAP)
export const sop2Localization = [
  {
    metric: "Mean IoU (Vehicle Box)",
    baseline: 0.741,
    cmt: 0.811,
    delta: 0.07,
    W: 0,
    p: 0.0,
    interpretation: "Significant improvement",
  },
  {
    metric: "mAP@50 (Parts)",
    baseline: 0.708,
    cmt: 0.785,
    delta: 0.077,
    W: 0,
    p: 0.0,
    interpretation: "Significant improvement",
  },
  {
    metric: "mAP@75 (Parts)",
    baseline: 0.622,
    cmt: 0.7,
    delta: 0.077,
    W: 0,
    p: 0.0,
    interpretation: "Significant improvement",
  },
];

// SOP 3 — Occlusion robustness (Clean / Low / Mid / High)
export const sop3Occlusion = {
  conditions: [
    {
      level: "Clean",
      data: [
        {
          level: "Type",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.919,
              cmt: 0.954,
              delta: 0.035,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.908,
              cmt: 0.947,
              delta: 0.039,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.915,
              cmt: 0.951,
              delta: 0.036,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.916,
              cmt: 0.945,
              delta: 0.029,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Make",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.879,
              cmt: 0.923,
              delta: 0.043,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.865,
              cmt: 0.91,
              delta: 0.046,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.866,
              cmt: 0.91,
              delta: 0.044,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.865,
              cmt: 0.913,
              delta: 0.047,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Model",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.824,
              cmt: 0.882,
              delta: 0.058,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.82,
              cmt: 0.875,
              delta: 0.055,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.819,
              cmt: 0.876,
              delta: 0.057,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.814,
              cmt: 0.874,
              delta: 0.06,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Vehicle IoU",
          metrics: [
            {
              metric: "Mean IoU",
              baseline: 0.782,
              cmt: 0.841,
              delta: 0.059,
              W: 0,
              p: 0.0,
            },
          ],
        },
      ],
    },
    {
      level: "Low",
      data: [
        {
          level: "Type",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.785,
              cmt: 0.898,
              delta: 0.113,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.773,
              cmt: 0.89,
              delta: 0.117,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.779,
              cmt: 0.894,
              delta: 0.114,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.777,
              cmt: 0.89,
              delta: 0.113,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Make",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.729,
              cmt: 0.865,
              delta: 0.137,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.717,
              cmt: 0.853,
              delta: 0.136,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.724,
              cmt: 0.858,
              delta: 0.134,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.724,
              cmt: 0.854,
              delta: 0.13,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Model",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.682,
              cmt: 0.833,
              delta: 0.15,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.668,
              cmt: 0.824,
              delta: 0.155,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.668,
              cmt: 0.819,
              delta: 0.151,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.667,
              cmt: 0.822,
              delta: 0.155,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Vehicle IoU",
          metrics: [
            {
              metric: "Mean IoU",
              baseline: 0.702,
              cmt: 0.804,
              delta: 0.103,
              W: 0,
              p: 0.0,
            },
          ],
        },
      ],
    },
    {
      level: "Mid",
      data: [
        {
          level: "Type",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.561,
              cmt: 0.76,
              delta: 0.2,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.545,
              cmt: 0.744,
              delta: 0.2,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.546,
              cmt: 0.748,
              delta: 0.202,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.543,
              cmt: 0.741,
              delta: 0.197,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Make",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.506,
              cmt: 0.723,
              delta: 0.217,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.499,
              cmt: 0.714,
              delta: 0.215,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.506,
              cmt: 0.709,
              delta: 0.203,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.496,
              cmt: 0.714,
              delta: 0.218,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Model",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.469,
              cmt: 0.681,
              delta: 0.213,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.45,
              cmt: 0.665,
              delta: 0.215,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.455,
              cmt: 0.667,
              delta: 0.212,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.455,
              cmt: 0.667,
              delta: 0.212,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Vehicle IoU",
          metrics: [
            {
              metric: "Mean IoU",
              baseline: 0.518,
              cmt: 0.685,
              delta: 0.167,
              W: 0,
              p: 0.0,
            },
          ],
        },
      ],
    },
    {
      level: "High",
      data: [
        {
          level: "Type",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.261,
              cmt: 0.522,
              delta: 0.26,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.254,
              cmt: 0.512,
              delta: 0.257,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.256,
              cmt: 0.511,
              delta: 0.255,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.266,
              cmt: 0.514,
              delta: 0.248,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Make",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.228,
              cmt: 0.478,
              delta: 0.25,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.211,
              cmt: 0.478,
              delta: 0.267,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.218,
              cmt: 0.472,
              delta: 0.255,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.206,
              cmt: 0.48,
              delta: 0.274,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Model",
          metrics: [
            {
              metric: "Accuracy",
              baseline: 0.185,
              cmt: 0.448,
              delta: 0.262,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Precision",
              baseline: 0.17,
              cmt: 0.436,
              delta: 0.266,
              W: 0,
              p: 0.0,
            },
            {
              metric: "Recall",
              baseline: 0.177,
              cmt: 0.441,
              delta: 0.264,
              W: 0,
              p: 0.0,
            },
            {
              metric: "F1",
              baseline: 0.177,
              cmt: 0.427,
              delta: 0.25,
              W: 0,
              p: 0.0,
            },
          ],
        },
        {
          level: "Vehicle IoU",
          metrics: [
            {
              metric: "Mean IoU",
              baseline: 0.238,
              cmt: 0.457,
              delta: 0.218,
              W: 0,
              p: 0.0,
            },
          ],
        },
      ],
    },
  ],
  friedmanTest: {
    chi2: 86.76,
    p: 0.0,
    interpretation: "Significant trend — CMT gains increase with occlusion severity.",
  },
};

// SOP 4 — Efficiency / Cost
export const sop4Efficiency = [
  {
    metric: "Latency (ms/frame)",
    baseline: 21.87,
    cmt: 23.31,
    delta: 1.44,
    W: 23,
    p: 0.0,
    interpretation: "Significant difference (unexpected)",
  },
  {
    metric: "GFLOPs",
    baseline: 7.52,
    cmt: 7.8,
    delta: 0.28,
    W: 21,
    p: 0.0,
    interpretation: "Significant difference (unexpected)",
  },
  {
    metric: "GPU Usage (%)",
    baseline: 70.1,
    cmt: 72.67,
    delta: 2.56,
    W: 6,
    p: 0.0,
    interpretation: "Significant difference (unexpected)",
  },
  {
    metric: "Power (W)",
    baseline: 110.8,
    cmt: 112.92,
    delta: 2.12,
    W: 36,
    p: 0.0,
    interpretation: "Significant difference (unexpected)",
  },
  {
    metric: "Memory (GB)",
    baseline: 4.55,
    cmt: 4.65,
    delta: 0.1,
    W: 62,
    p: 0.0002,
    interpretation: "Significant difference (unexpected)",
  },
];

// SOP Overview — no JSON provided, keep as empty array so the page logic is safe.
export const sopOverview = [];
